# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Euc_dist <- function(A, B) {
    .Call(`_convexhull_Euc_dist`, A, B)
}

find_left <- function(points) {
    .Call(`_convexhull_find_left`, points)
}

jarvis_march_cpp <- function(input) {
    .Call(`_convexhull_jarvis_march_cpp`, input)
}

remove_duplicates <- function(input) {
    .Call(`_convexhull_remove_duplicates`, input)
}

